import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manci
 */
public class funciones_productoss extends javax.swing.JInternalFrame {
Conectar con;
    /**
     * Creates new form funciones_productoss
     */
    public funciones_productoss() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcodigopro = new javax.swing.JTextField();
        btm_buscar = new javax.swing.JButton();
        lvl_id_producto = new javax.swing.JLabel();
        lvl_precio = new javax.swing.JLabel();
        txtnombrepro = new javax.swing.JTextField();
        lvl_nombre_producto = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        lvl_descripcion = new javax.swing.JLabel();
        btm_guardar = new javax.swing.JButton();
        btm_eliminar = new javax.swing.JButton();
        btm_nuevo = new javax.swing.JButton();
        txtfechain = new javax.swing.JTextField();
        lvl_fecha_ingreso_2 = new javax.swing.JLabel();
        txtfechaca = new javax.swing.JTextField();
        lvl_fecha_caducidad_2 = new javax.swing.JLabel();
        txtcategoria = new javax.swing.JTextField();
        lvl_categoria_2 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        lvl_cantidad_2 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        lvl_marca_ = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtfechain1 = new javax.swing.JTextField();
        lvl_iva = new javax.swing.JLabel();
        txtiva = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Funciones productos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Funciones producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 518, 70));

        txtcodigopro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoproKeyTyped(evt);
            }
        });
        getContentPane().add(txtcodigopro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, 30));

        btm_buscar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btm_buscar.setText("Buscar");
        btm_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 80, 30));

        lvl_id_producto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_id_producto.setForeground(new java.awt.Color(255, 255, 255));
        lvl_id_producto.setText("ID producto:");
        getContentPane().add(lvl_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lvl_precio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_precio.setForeground(new java.awt.Color(255, 255, 255));
        lvl_precio.setText("Precio:");
        getContentPane().add(lvl_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        getContentPane().add(txtnombrepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 160, 30));

        lvl_nombre_producto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_nombre_producto.setForeground(new java.awt.Color(255, 255, 255));
        lvl_nombre_producto.setText("Nombre producto:");
        getContentPane().add(lvl_nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 160, 30));

        txtdescripcion.setColumns(20);
        txtdescripcion.setRows(5);
        jScrollPane1.setViewportView(txtdescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 160, 80));

        lvl_descripcion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_descripcion.setForeground(new java.awt.Color(255, 255, 255));
        lvl_descripcion.setText("Descripcion:");
        getContentPane().add(lvl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        btm_guardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btm_guardar.setText("Guardar");
        btm_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 100, 40));

        btm_eliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btm_eliminar.setText("Eliminar");
        btm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 100, 40));

        btm_nuevo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btm_nuevo.setText("Limpiar");
        btm_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btm_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 90, 40));

        txtfechain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechainKeyTyped(evt);
            }
        });
        getContentPane().add(txtfechain, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 30));

        lvl_fecha_ingreso_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_fecha_ingreso_2.setForeground(new java.awt.Color(255, 255, 255));
        lvl_fecha_ingreso_2.setText("Fecha de ingreso:");
        getContentPane().add(lvl_fecha_ingreso_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        txtfechaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechacaKeyTyped(evt);
            }
        });
        getContentPane().add(txtfechaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 140, 30));

        lvl_fecha_caducidad_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_fecha_caducidad_2.setForeground(new java.awt.Color(255, 255, 255));
        lvl_fecha_caducidad_2.setText("Fecha de caducidad:");
        getContentPane().add(lvl_fecha_caducidad_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        txtcategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcategoriaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 139, 30));

        lvl_categoria_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_categoria_2.setForeground(new java.awt.Color(255, 255, 255));
        lvl_categoria_2.setText("Categoria:");
        getContentPane().add(lvl_categoria_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 140, 30));

        lvl_cantidad_2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_cantidad_2.setForeground(new java.awt.Color(255, 255, 255));
        lvl_cantidad_2.setText("Cantidad:");
        getContentPane().add(lvl_cantidad_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));
        getContentPane().add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 140, 30));

        lvl_marca_.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_marca_.setForeground(new java.awt.Color(255, 255, 255));
        lvl_marca_.setText("Marca:");
        getContentPane().add(lvl_marca_, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Requerido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escriba el id producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Requerido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Requerido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Requerido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Requerido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Requerido");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Requerido");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Requerido");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, -1, -1));

        txtfechain1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechain1KeyTyped(evt);
            }
        });
        getContentPane().add(txtfechain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 30));

        lvl_iva.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lvl_iva.setForeground(new java.awt.Color(255, 255, 255));
        lvl_iva.setText("Iva");
        getContentPane().add(lvl_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 40, 20));

        txtiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtivaActionPerformed(evt);
            }
        });
        txtiva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtivaKeyTyped(evt);
            }
        });
        getContentPane().add(txtiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 140, 30));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Requerido");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_3.png"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoproKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoproKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtcodigoproKeyTyped

    private void btm_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_buscarActionPerformed
        con=new Conectar();
        Connection reg= con.getConnection();
        PreparedStatement pps;
        ResultSet rs;

        try {
            pps = reg.prepareStatement("SELECT* FROM producto WHERE id_producto=?");
            pps.setString(1,txtcodigopro.getText());

            rs=pps.executeQuery();

            if(rs.next()){
                txtnombrepro.setText(rs.getString("nombre_producto"));
                txtprecio.setText(rs.getString("precio"));
                txtiva.setText(rs.getString("iva"));
                txtdescripcion.setText(rs.getString("descripcion"));
                txtfechain.setText(rs.getString("fecha_ingreso"));
                txtfechaca.setText(rs.getString("fecha_caducidad"));
                txtcategoria.setText(rs.getString("categoria"));
                txtcantidad.setText(rs.getString("cantidad"));
                txtmarca.setText(rs.getString("marca"));
                JOptionPane.showMessageDialog(null, "Datos encontrados");
            }else{
                JOptionPane.showMessageDialog(null, "Datos no encontrados");
            }
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btm_buscarActionPerformed

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtprecioKeyTyped

    private void btm_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_guardarActionPerformed
        con=new Conectar();
        Connection reg= con.getConnection();
        PreparedStatement pps;
        
        try {
            pps = reg.prepareStatement("UPDATE producto SET nombre_producto=?,precio=?,iva=?,descripcion=?,fecha_ingreso=?,fecha_caducidad=?,categoria=?,cantidad=?,marca=? WHERE id_producto=?");
            pps.setString(1,txtnombrepro.getText());
            pps.setString(2,txtprecio.getText());
             pps.setString(3,txtiva.getText());
            pps.setString(4,txtdescripcion.getText());
            pps.setString(5,txtfechain.getText());
            pps.setString(6,txtfechaca.getText());
            pps.setString(7,txtcategoria.getText());
            pps.setString(8,txtcantidad.getText());
            pps.setString(9,txtmarca.getText());
            pps.setString(10,txtcodigopro.getText());
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos Actualizados");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"ERROR "+ex.getMessage());
        }

    }//GEN-LAST:event_btm_guardarActionPerformed

    private void btm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_eliminarActionPerformed
        con=new Conectar();
        Connection reg= con.getConnection();
        PreparedStatement pps;
        PreparedStatement ppd;

        ResultSet rs;

        try {
            ppd = reg.prepareStatement("DELETE FROM control WHERE id_producto=?");
            ppd.setInt(1, Integer.parseInt(txtcodigopro.getText()));
            ppd.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pps = reg.prepareStatement("DELETE FROM producto WHERE id_producto=?");
            pps.setInt(1, Integer.parseInt(txtcodigopro.getText()));
            pps.executeUpdate();

            int res=pps.executeUpdate();

            if(res>0){
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }else{
                JOptionPane.showMessageDialog(null, "Producto eliminado");
            }
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btm_eliminarActionPerformed

    private void btm_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_nuevoActionPerformed
        txtcodigopro.setText("");
        txtnombrepro.setText("");
        txtprecio.setText("");
        txtdescripcion.setText("");
        txtfechain.setText("");
        txtfechaca.setText("");
        txtiva.setText("");
        txtcategoria.setText("");
        txtcantidad.setText("");
        txtmarca.setText("");

    }//GEN-LAST:event_btm_nuevoActionPerformed

    private void txtfechainKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechainKeyTyped
        char c = evt.getKeyChar();
        if ((c<'0' || c>'9') && (c<'/' || c>'/'))evt.consume();
    }//GEN-LAST:event_txtfechainKeyTyped

    private void txtfechacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechacaKeyTyped
        char c = evt.getKeyChar();
        if ((c<'0' || c>'9') && (c<'/' || c>'/'))evt.consume();
    }//GEN-LAST:event_txtfechacaKeyTyped

    private void txtcategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcategoriaKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '|| c>' '))evt.consume();
    }//GEN-LAST:event_txtcategoriaKeyTyped

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtfechain1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechain1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechain1KeyTyped

    private void txtivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtivaActionPerformed

    private void txtivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtivaKeyTyped

    }//GEN-LAST:event_txtivaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_buscar;
    private javax.swing.JButton btm_eliminar;
    private javax.swing.JButton btm_guardar;
    private javax.swing.JButton btm_nuevo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lvl_cantidad_2;
    private javax.swing.JLabel lvl_categoria_2;
    private javax.swing.JLabel lvl_descripcion;
    private javax.swing.JLabel lvl_fecha_caducidad_2;
    private javax.swing.JLabel lvl_fecha_ingreso_2;
    private javax.swing.JLabel lvl_id_producto;
    private javax.swing.JLabel lvl_iva;
    private javax.swing.JLabel lvl_marca_;
    private javax.swing.JLabel lvl_nombre_producto;
    private javax.swing.JLabel lvl_precio;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtcodigopro;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtfechaca;
    private javax.swing.JTextField txtfechain;
    private javax.swing.JTextField txtfechain1;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtnombrepro;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
