
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manci
 */
public class funciones_proveedorr extends javax.swing.JInternalFrame {

    Conectar con;

    /**
     * Creates new form funciones_proveedorr
     */
    public funciones_proveedorr() {
        initComponents();
    }

    private void limpiar() {
        tnip.setText(null);
        tid_proveedor.setText(null);
        tnombre_proveedor.setText(null);
        tfecha_ingreso.setText(null);
        tcantidad_unidades.setText(null);
        tcodigo_pedido.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        tid_proveedor = new javax.swing.JTextField();
        lvl_Id_Proveedor = new javax.swing.JLabel();
        tnombre_proveedor = new javax.swing.JTextField();
        lvlv_Nombre_Proveedor = new javax.swing.JLabel();
        tfecha_ingreso = new javax.swing.JTextField();
        lvl_Fecha_Ingreso1 = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        btn_eliminar1 = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        tcodigo_pedido = new javax.swing.JTextField();
        lvl_Codigo_Pedido = new javax.swing.JLabel();
        tcantidad_unidades = new javax.swing.JTextField();
        lvl_Cantidad_Unidaes1 = new javax.swing.JLabel();
        tnip = new javax.swing.JTextField();
        lvl_cc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Funciones proveedor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar/Buscar Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Para poder editar y buscar debe existir el proveedor! ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        btn_buscar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 90, 30));

        tid_proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tid_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tid_proveedorActionPerformed(evt);
            }
        });
        tid_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tid_proveedorKeyTyped(evt);
            }
        });
        getContentPane().add(tid_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, 30));

        lvl_Id_Proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_Id_Proveedor.setForeground(new java.awt.Color(255, 255, 255));
        lvl_Id_Proveedor.setText("Id Proveedor");
        getContentPane().add(lvl_Id_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 20));

        tnombre_proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tnombre_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnombre_proveedorActionPerformed(evt);
            }
        });
        tnombre_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnombre_proveedorKeyTyped(evt);
            }
        });
        getContentPane().add(tnombre_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 130, 30));

        lvlv_Nombre_Proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvlv_Nombre_Proveedor.setForeground(new java.awt.Color(255, 255, 255));
        lvlv_Nombre_Proveedor.setText("Nombre Proveedor");
        getContentPane().add(lvlv_Nombre_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        tfecha_ingreso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfecha_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfecha_ingresoActionPerformed(evt);
            }
        });
        tfecha_ingreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfecha_ingresoKeyTyped(evt);
            }
        });
        getContentPane().add(tfecha_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 130, 30));

        lvl_Fecha_Ingreso1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_Fecha_Ingreso1.setForeground(new java.awt.Color(255, 255, 255));
        lvl_Fecha_Ingreso1.setText("Fecha Ingreso");
        getContentPane().add(lvl_Fecha_Ingreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        btn_editar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 120, 40));

        btn_eliminar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_eliminar1.setText("Eliminar");
        btn_eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 120, 40));

        btn_limpiar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 120, 40));

        tcodigo_pedido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tcodigo_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcodigo_pedidoActionPerformed(evt);
            }
        });
        tcodigo_pedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcodigo_pedidoKeyTyped(evt);
            }
        });
        getContentPane().add(tcodigo_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 140, 30));

        lvl_Codigo_Pedido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_Codigo_Pedido.setForeground(new java.awt.Color(255, 255, 255));
        lvl_Codigo_Pedido.setText("Codigo Pedido");
        getContentPane().add(lvl_Codigo_Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, 20));

        tcantidad_unidades.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tcantidad_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcantidad_unidadesActionPerformed(evt);
            }
        });
        tcantidad_unidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcantidad_unidadesKeyTyped(evt);
            }
        });
        getContentPane().add(tcantidad_unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 140, 30));

        lvl_Cantidad_Unidaes1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_Cantidad_Unidaes1.setForeground(new java.awt.Color(255, 255, 255));
        lvl_Cantidad_Unidaes1.setText("Cantidad Unidades");
        getContentPane().add(lvl_Cantidad_Unidaes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, 20));

        tnip.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnipActionPerformed(evt);
            }
        });
        tnip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnipKeyTyped(evt);
            }
        });
        getContentPane().add(tnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 140, 30));

        lvl_cc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_cc.setForeground(new java.awt.Color(255, 255, 255));
        lvl_cc.setText("NIT");
        getContentPane().add(lvl_cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 60, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escriba el id prooveedor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Requerido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Requerido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Requerido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Requerido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Requerido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        con = new Conectar();
        //Creación de un try para mostrar un mensaje en vez de un error en la consola
        try {
            Connection r = con.getConnection();
            //Acción que se va realizar en la base de datos
            PreparedStatement ingresar = r.prepareStatement("SELECT * FROM proveedor WHERE id_proveedor=?");
            ingresar.setString(1, tid_proveedor.getText());
            ResultSet busqueda = ingresar.executeQuery();
            //Creación de un if
            if (busqueda.next()) {
                tnip.setText(busqueda.getString("nit"));
                tnombre_proveedor.setText(busqueda.getString("nombre_proveedor"));
                tfecha_ingreso.setText(busqueda.getString("fecha_ingreso"));
                tcantidad_unidades.setText(busqueda.getString("cantidad_unidades"));
                tcodigo_pedido.setText(busqueda.getString("codigo_pedido"));
                JOptionPane.showMessageDialog(null, "Busqueda correcta");
            } else {
                JOptionPane.showMessageDialog(null, "No existe esta identificación de proveedor");
                limpiar();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la consola");
            System.out.println("Error en la busqueda:" + e);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tid_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tid_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tid_proveedorActionPerformed

    private void tid_proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tid_proveedorKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_tid_proveedorKeyTyped

    private void tnombre_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnombre_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnombre_proveedorActionPerformed

    private void tnombre_proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnombre_proveedorKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' '))
            evt.consume();
    }//GEN-LAST:event_tnombre_proveedorKeyTyped

    private void tfecha_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfecha_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfecha_ingresoActionPerformed

    private void tfecha_ingresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfecha_ingresoKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < '/' || c > '/'))
            evt.consume();
    }//GEN-LAST:event_tfecha_ingresoKeyTyped

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        con = new Conectar();
        //Creación de un try para mostrar un mensaje en vez de un error en la consola
        try {
            Connection r = con.getConnection();
            //Acción que se va realizar en la base de datos
            PreparedStatement ingresar = r.prepareStatement("UPDATE proveedor SET nit=?,nombre_proveedor=?,fecha_ingreso=?,cantidad_unidades=?,codigo_pedido=? WHERE id_proveedor=?");
            ingresar.setString(1, tnip.getText());
            ingresar.setString(2, tnombre_proveedor.getText());
            ingresar.setString(3, tfecha_ingreso.getText());
            ingresar.setString(4, tcantidad_unidades.getText());
            ingresar.setString(5, tcodigo_pedido.getText());
            ingresar.setString(6, tid_proveedor.getText());
            int actualizacion = ingresar.executeUpdate();
            //Creación de un if
            if (actualizacion > 0) {
                JOptionPane.showMessageDialog(null, "Actualización exitosa");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Actualización fallida\nNo se puede cambiar la id_empleado");
                limpiar();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la consola\nNo existe el codigo en la tabla pedido");
            System.out.println("Error en la actualización:" + e);
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar1ActionPerformed

        con = new Conectar();
        Connection reg = con.getConnection();
        PreparedStatement pps;
        PreparedStatement ppd;
        PreparedStatement ppf;
        ResultSet rs;

        try {
            ppf = reg.prepareStatement("SET FOREIGN_KEY_CHECKS=0;");
            ppf.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ppd = reg.prepareStatement("DELETE FROM pedido WHERE codigo_pedido=?");
            ppd.setInt(1, Integer.parseInt(tcodigo_pedido.getText()));
            ppd.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pps = reg.prepareStatement("DELETE FROM proveedor WHERE id_proveedor=?");
            pps.setInt(1, Integer.parseInt(tid_proveedor.getText()));
            pps.executeUpdate();

            int res = pps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            } else {
                JOptionPane.showMessageDialog(null, "Persona eliminada");
            }
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_eliminar1ActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        tid_proveedor.setText("");
        tnombre_proveedor.setText("");
        tfecha_ingreso.setText("");
        tnip.setText("");
        tcantidad_unidades.setText("");
        tcodigo_pedido.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void tcodigo_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcodigo_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcodigo_pedidoActionPerformed

    private void tcodigo_pedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcodigo_pedidoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_tcodigo_pedidoKeyTyped

    private void tcantidad_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcantidad_unidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcantidad_unidadesActionPerformed

    private void tcantidad_unidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcantidad_unidadesKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_tcantidad_unidadesKeyTyped

    private void tnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnipActionPerformed

    private void tnipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnipKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9')
            evt.consume();
    }//GEN-LAST:event_tnipKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar1;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lvl_Cantidad_Unidaes1;
    private javax.swing.JLabel lvl_Codigo_Pedido;
    private javax.swing.JLabel lvl_Fecha_Ingreso1;
    private javax.swing.JLabel lvl_Id_Proveedor;
    private javax.swing.JLabel lvl_cc;
    private javax.swing.JLabel lvlv_Nombre_Proveedor;
    private javax.swing.JTextField tcantidad_unidades;
    private javax.swing.JTextField tcodigo_pedido;
    private javax.swing.JTextField tfecha_ingreso;
    private javax.swing.JTextField tid_proveedor;
    private javax.swing.JTextField tnip;
    private javax.swing.JTextField tnombre_proveedor;
    // End of variables declaration//GEN-END:variables
}
