import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manci
 */
public class funciones_ventass extends javax.swing.JInternalFrame {
Conectar con;
    /**
     * Creates new form funciones_ventass
     */
    public funciones_ventass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        btm_buscar = new javax.swing.JButton();
        txt_id_venta = new javax.swing.JTextField();
        txt_nombre_producto = new javax.swing.JTextField();
        txt_producto = new javax.swing.JLabel();
        id_ventap = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JLabel();
        txt_cantidadp = new javax.swing.JTextField();
        btm_editar = new javax.swing.JButton();
        btm_eliminar = new javax.swing.JButton();
        btm_limpiar = new javax.swing.JButton();
        txt_codp = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JLabel();
        txt_nombre_empleado = new javax.swing.JTextField();
        txt_empleado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Funciones ventas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Funciones venta");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        btm_buscar.setText("Buscar");
        btm_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 80, 30));

        txt_id_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_ventaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, 30));

        txt_nombre_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_productoActionPerformed(evt);
            }
        });
        txt_nombre_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_productoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, 30));

        txt_producto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_producto.setForeground(new java.awt.Color(255, 255, 255));
        txt_producto.setText("Nombre Producto");
        getContentPane().add(txt_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        id_ventap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        id_ventap.setForeground(new java.awt.Color(255, 255, 255));
        id_ventap.setText("id_venta");
        getContentPane().add(id_ventap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txt_cantidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        txt_cantidad.setText("Cantidad");
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_cantidadp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadpActionPerformed(evt);
            }
        });
        txt_cantidadp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadpKeyTyped(evt);
            }
        });
        getContentPane().add(txt_cantidadp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 140, 30));

        btm_editar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btm_editar.setText("Editar");
        btm_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 100, 30));

        btm_eliminar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btm_eliminar.setText("Eliminar");
        btm_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 100, 30));

        btm_limpiar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btm_limpiar.setText("Limpiar");
        btm_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 100, 30));

        txt_codp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codpActionPerformed(evt);
            }
        });
        txt_codp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codpKeyTyped(evt);
            }
        });
        getContentPane().add(txt_codp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 140, 30));

        txt_codigo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_codigo.setForeground(new java.awt.Color(255, 255, 255));
        txt_codigo.setText("codigo");
        getContentPane().add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        txt_nombre_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_empleadoActionPerformed(evt);
            }
        });
        txt_nombre_empleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombre_empleadoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 140, 30));

        txt_empleado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_empleado.setForeground(new java.awt.Color(255, 255, 255));
        txt_empleado.setText("Nombre empleado");
        getContentPane().add(txt_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escriba el id venta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Requerido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Requerido");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Requerido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Requerido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_3.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_buscarActionPerformed
        con = new Conectar();
        //Creación de un try para mostrar un mensaje en vez de un error en la consola
        try {
            Connection r = con.getConnection();
            //Acción que se va realizar en la base de datos
            PreparedStatement ingresar = r.prepareStatement("SELECT * FROM venta WHERE id_venta=?");
            ingresar.setString(1, txt_id_venta.getText());
            ResultSet busqueda = ingresar.executeQuery();
            //Creación de un if
            if (busqueda.next()) {
                txt_id_venta.setText(busqueda.getString("id_venta"));
                txt_nombre_producto.setText(busqueda.getString("producto"));
                txt_cantidadp.setText(busqueda.getString("cantidad_productos"));
                txt_nombre_empleado.setText(busqueda.getString("nombre_empleado"));
                txt_codp.setText(busqueda.getString("id_producto"));

            } else {
                JOptionPane.showMessageDialog(null, "No existe esta venta con esta identificacion");

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error en la consola");
            System.out.println("Error en la busqueda:" + e);
        }
    }//GEN-LAST:event_btm_buscarActionPerformed

    private void txt_id_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_ventaActionPerformed

    }//GEN-LAST:event_txt_id_ventaActionPerformed

    private void txt_nombre_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_productoActionPerformed

    private void txt_nombre_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_productoKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '|| c>' '))evt.consume();
    }//GEN-LAST:event_txt_nombre_productoKeyTyped

    private void txt_cantidadpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadpActionPerformed

    private void txt_cantidadpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadpKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txt_cantidadpKeyTyped

    private void btm_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_editarActionPerformed

        con=new Conectar();
        Connection reg= con.getConnection();
        PreparedStatement pps;
        ResultSet rs;
        try {
            pps = reg.prepareStatement("UPDATE venta SET producto =?,cantidad_productos=?,nombre_empleado=?,id_producto=? WHERE id_venta=?");
            pps.setString(1,txt_nombre_producto.getText());
            pps.setString(2,txt_cantidadp.getText());
            pps.setString(3,txt_nombre_empleado.getText());
            pps.setString(4,txt_codp.getText());
            pps.setString(5,txt_id_venta.getText());
            
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos Actualizados");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"ERROR ");
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btm_editarActionPerformed

    private void btm_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_eliminarActionPerformed
        con=new Conectar();
        Connection reg= con.getConnection();
        PreparedStatement pps;
        PreparedStatement ppd;
        PreparedStatement ppf;
        ResultSet rs;

        try {
            ppf = reg.prepareStatement("SET FOREIGN_KEY_CHECKS=0;");
            ppf.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ppd = reg.prepareStatement("DELETE FROM venta WHERE id_venta=?");
            ppd.setInt(1, Integer.parseInt(txt_id_venta.getText()));
            ppd.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pps = reg.prepareStatement("DELETE FROM producto WHERE id_venta=?");
            pps.setInt(1, Integer.parseInt(txt_id_venta.getText()));
            pps.executeUpdate();

            int res=pps.executeUpdate();

            if(res>0){
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }else{
                JOptionPane.showMessageDialog(null, "venta eliminada");
            }
        } catch (SQLException ex) {
            Logger.getLogger(funciones_productoss.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btm_eliminarActionPerformed

    private void btm_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_limpiarActionPerformed
        txt_id_venta.setText("");
        txt_nombre_producto.setText("");
        txt_cantidadp.setText("");
        txt_nombre_empleado.setText("");
        txt_codp.setText("");
    }//GEN-LAST:event_btm_limpiarActionPerformed

    private void txt_codpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codpActionPerformed

    private void txt_codpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codpKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txt_codpKeyTyped

    private void txt_nombre_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_empleadoActionPerformed

    private void txt_nombre_empleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_empleadoKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' '|| c>' '))evt.consume();
    }//GEN-LAST:event_txt_nombre_empleadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_buscar;
    private javax.swing.JButton btm_editar;
    private javax.swing.JButton btm_eliminar;
    private javax.swing.JButton btm_limpiar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel id_ventap;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txt_cantidad;
    private javax.swing.JTextField txt_cantidadp;
    private javax.swing.JLabel txt_codigo;
    private javax.swing.JTextField txt_codp;
    private javax.swing.JLabel txt_empleado;
    public javax.swing.JTextField txt_id_venta;
    private javax.swing.JTextField txt_nombre_empleado;
    private javax.swing.JTextField txt_nombre_producto;
    private javax.swing.JLabel txt_producto;
    // End of variables declaration//GEN-END:variables
}
