/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexander
 */
public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public menu_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Escritorio = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Productos = new javax.swing.JMenu();
        registrar_p = new javax.swing.JMenuItem();
        funciones_p = new javax.swing.JMenuItem();
        Listado_p = new javax.swing.JMenuItem();
        ventas = new javax.swing.JMenu();
        registrar_v = new javax.swing.JMenuItem();
        funciones_v = new javax.swing.JMenuItem();
        listado_v = new javax.swing.JMenuItem();
        empleados = new javax.swing.JMenu();
        funciones_e = new javax.swing.JMenuItem();
        Listado_e = new javax.swing.JMenuItem();
        proveedores = new javax.swing.JMenu();
        registrar_pr = new javax.swing.JMenuItem();
        funciones_pr = new javax.swing.JMenuItem();
        Listado_pr = new javax.swing.JMenuItem();
        cuenta = new javax.swing.JMenu();
        registrar_cu = new javax.swing.JMenuItem();
        funciones_cu = new javax.swing.JMenuItem();
        Listado_cu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario_inicio.png"))); // NOI18N
        jLabel2.setNextFocusableComponent(Escritorio);
        Escritorio.add(jLabel2);
        jLabel2.setBounds(10, 160, 256, 256);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Big Pharma");
        Escritorio.add(jLabel5);
        jLabel5.setBounds(60, 80, 169, 42);

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 102));
        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFocusTraversalPolicyProvider(true);
        jMenuBar1.setMaximumSize(new java.awt.Dimension(300, 32769));

        Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_inventory_maintenance_product_box_boxes_2326 (1).png"))); // NOI18N
        Productos.setText("Productos");
        Productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Productos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Productos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Productos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        registrar_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro.png"))); // NOI18N
        registrar_p.setText("Registrar");
        registrar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_pActionPerformed(evt);
            }
        });
        Productos.add(registrar_p);

        funciones_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/funciones.png"))); // NOI18N
        funciones_p.setText("Funciones");
        funciones_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funciones_pActionPerformed(evt);
            }
        });
        Productos.add(funciones_p);

        Listado_p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listado.png"))); // NOI18N
        Listado_p.setText("Listado");
        Listado_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listado_pActionPerformed(evt);
            }
        });
        Productos.add(Listado_p);

        jMenuBar1.add(Productos);

        ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cashier_icon-icons.com_53629.png"))); // NOI18N
        ventas.setText("Ventas");

        registrar_v.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/shoppaymentorderbuy-11_icon-icons.com_73850.png"))); // NOI18N
        registrar_v.setText("Ventas");
        registrar_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_vActionPerformed(evt);
            }
        });
        ventas.add(registrar_v);

        funciones_v.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/funciones.png"))); // NOI18N
        funciones_v.setText("Funciones");
        funciones_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funciones_vActionPerformed(evt);
            }
        });
        ventas.add(funciones_v);

        listado_v.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listado.png"))); // NOI18N
        listado_v.setText("Listado ventas");
        listado_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listado_vActionPerformed(evt);
            }
        });
        ventas.add(listado_v);

        jMenuBar1.add(ventas);

        empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconfinder-3-avatar-2754579_120516 (1).png"))); // NOI18N
        empleados.setText("Empleados");

        funciones_e.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Datos empleado.png"))); // NOI18N
        funciones_e.setText("Datos empleados");
        funciones_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funciones_eActionPerformed(evt);
            }
        });
        empleados.add(funciones_e);

        Listado_e.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listado.png"))); // NOI18N
        Listado_e.setText("Listado empleados");
        Listado_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listado_eActionPerformed(evt);
            }
        });
        empleados.add(Listado_e);

        jMenuBar1.add(empleados);

        proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/transfer_man_employee_user_avatar_arrow_refresh_icon_141997.png"))); // NOI18N
        proveedores.setText("Proveedores");

        registrar_pr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo proveedor.png"))); // NOI18N
        registrar_pr.setText("Nuevo proveedor");
        registrar_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_prActionPerformed(evt);
            }
        });
        proveedores.add(registrar_pr);

        funciones_pr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edicion.png"))); // NOI18N
        funciones_pr.setText("Funciones");
        funciones_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funciones_prActionPerformed(evt);
            }
        });
        proveedores.add(funciones_pr);

        Listado_pr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listado.png"))); // NOI18N
        Listado_pr.setText("Listado");
        Listado_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listado_prActionPerformed(evt);
            }
        });
        proveedores.add(Listado_pr);

        jMenuBar1.add(proveedores);

        cuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/card_account_details_star_outline_icon_139051.png"))); // NOI18N
        cuenta.setText("Cuentas");

        registrar_cu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/account_add_icon_140042.png"))); // NOI18N
        registrar_cu.setText("Registrar Cuentas");
        registrar_cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_cuActionPerformed(evt);
            }
        });
        cuenta.add(registrar_cu);

        funciones_cu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/account_edit_outline_icon_140057.png"))); // NOI18N
        funciones_cu.setText("Funciones Cuentas");
        funciones_cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funciones_cuActionPerformed(evt);
            }
        });
        cuenta.add(funciones_cu);

        Listado_cu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/note-with-list-square-outlined-interface-symbol_icon-icons.com_57784.png"))); // NOI18N
        Listado_cu.setText("Listado Cuentas");
        Listado_cu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listado_cuActionPerformed(evt);
            }
        });
        cuenta.add(Listado_cu);

        jMenuBar1.add(cuenta);

        jMenu1.setText("Copias de seguridad");

        jMenuItem4.setText("Crear y Restaurar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Listado_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listado_eActionPerformed
        tabla_empleadoo abrir= new tabla_empleadoo();
     Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_Listado_eActionPerformed

    private void registrar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_pActionPerformed
      registrar_productoss abrir= new registrar_productoss();
      Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_registrar_pActionPerformed

    private void Listado_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listado_pActionPerformed
       tabla_productoss abrir= new tabla_productoss();
      Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_Listado_pActionPerformed

    private void funciones_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funciones_pActionPerformed
       funciones_productoss abrir= new funciones_productoss();
       Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_funciones_pActionPerformed

    private void registrar_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_vActionPerformed
       registrar_ventaa abrir2= new registrar_ventaa();
      Escritorio.add(abrir2);
      abrir2.show();
      factura_2 abrir= new factura_2();
      Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_registrar_vActionPerformed

    private void funciones_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funciones_vActionPerformed
        funciones_ventass abrir= new funciones_ventass();
    Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_funciones_vActionPerformed

    private void listado_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listado_vActionPerformed
      tabla_ventaa abrir= new tabla_ventaa();
      Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_listado_vActionPerformed

    private void funciones_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funciones_eActionPerformed
      funciones_empleadoss abrir= new funciones_empleadoss();
      Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_funciones_eActionPerformed

    private void registrar_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_prActionPerformed
     registrar_proveedorr abrir= new registrar_proveedorr();
      Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_registrar_prActionPerformed

    private void funciones_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funciones_prActionPerformed
       funciones_proveedorr abrir= new funciones_proveedorr();
      Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_funciones_prActionPerformed

    private void Listado_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listado_prActionPerformed
       tabla_proveedoress abrir= new tabla_proveedoress();
      Escritorio.add(abrir);
      abrir.show();
    }//GEN-LAST:event_Listado_prActionPerformed

    private void registrar_cuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_cuActionPerformed
        registrar_cuentass abrir= new registrar_cuentass();
        Escritorio.add(abrir);
        abrir.show();
    }//GEN-LAST:event_registrar_cuActionPerformed

    private void funciones_cuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funciones_cuActionPerformed
        funciones_cuentass abrir= new funciones_cuentass();
        Escritorio.add(abrir);
        abrir.show();        
    }//GEN-LAST:event_funciones_cuActionPerformed

    private void Listado_cuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listado_cuActionPerformed
        tabla_cuentass abrir= new tabla_cuentass();
        Escritorio.add(abrir);
        abrir.show();        
    }//GEN-LAST:event_Listado_cuActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       copias_seguridad abrir= new copias_seguridad();
        Escritorio.add(abrir);
        abrir.show();  
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem Listado_cu;
    private javax.swing.JMenuItem Listado_e;
    private javax.swing.JMenuItem Listado_p;
    private javax.swing.JMenuItem Listado_pr;
    public javax.swing.JMenu Productos;
    public javax.swing.JMenu cuenta;
    private javax.swing.JMenu empleados;
    private javax.swing.JMenuItem funciones_cu;
    public javax.swing.JMenuItem funciones_e;
    public javax.swing.JMenuItem funciones_p;
    public javax.swing.JMenuItem funciones_pr;
    public javax.swing.JMenuItem funciones_v;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem listado_v;
    private javax.swing.JMenu proveedores;
    private javax.swing.JMenuItem registrar_cu;
    private javax.swing.JMenuItem registrar_p;
    public javax.swing.JMenuItem registrar_pr;
    private javax.swing.JMenuItem registrar_v;
    private javax.swing.JMenu ventas;
    // End of variables declaration//GEN-END:variables
}
