import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manci
 */
public class registrar_proveedorr extends javax.swing.JInternalFrame {
Conectar conect;
    /**
     * Creates new form registrar_proveedorr
     */
    public registrar_proveedorr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tid_proveedor = new javax.swing.JTextField();
        lvl_Id_Proveedor = new javax.swing.JLabel();
        tnip = new javax.swing.JTextField();
        lvl_cc = new javax.swing.JLabel();
        tnombre_proveedor = new javax.swing.JTextField();
        lvlv_Nombre_Proveedor = new javax.swing.JLabel();
        btn_registrar1 = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        tcodigo_pedido = new javax.swing.JTextField();
        lvl_Codigo_Pedido = new javax.swing.JLabel();
        tcantidad_unidades = new javax.swing.JTextField();
        tfecha_ingreso = new javax.swing.JTextField();
        lvl_Fecha_Ingreso1 = new javax.swing.JLabel();
        lvl_Cantidad_Unidaes1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar proveedor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Para poder registrar un preveedor debe existir un pedido! ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        tid_proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tid_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tid_proveedorActionPerformed(evt);
            }
        });
        tid_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tid_proveedorKeyTyped(evt);
            }
        });
        getContentPane().add(tid_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, 30));

        lvl_Id_Proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_Id_Proveedor.setForeground(new java.awt.Color(255, 255, 255));
        lvl_Id_Proveedor.setText("Id Proveedor");
        getContentPane().add(lvl_Id_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        tnip.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnipActionPerformed(evt);
            }
        });
        tnip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnipKeyTyped(evt);
            }
        });
        getContentPane().add(tnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 30));

        lvl_cc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_cc.setForeground(new java.awt.Color(255, 255, 255));
        lvl_cc.setText("NIT");
        getContentPane().add(lvl_cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 20));

        tnombre_proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tnombre_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnombre_proveedorActionPerformed(evt);
            }
        });
        tnombre_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnombre_proveedorKeyTyped(evt);
            }
        });
        getContentPane().add(tnombre_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 130, 30));

        lvlv_Nombre_Proveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvlv_Nombre_Proveedor.setForeground(new java.awt.Color(255, 255, 255));
        lvlv_Nombre_Proveedor.setText("Nombre Proveedor");
        getContentPane().add(lvlv_Nombre_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        btn_registrar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_registrar1.setText("Registrar");
        btn_registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        btn_nuevo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_nuevo.setText("Limpiar");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, 30));

        tcodigo_pedido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tcodigo_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcodigo_pedidoActionPerformed(evt);
            }
        });
        tcodigo_pedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcodigo_pedidoKeyTyped(evt);
            }
        });
        getContentPane().add(tcodigo_pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 130, 30));

        lvl_Codigo_Pedido.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_Codigo_Pedido.setForeground(new java.awt.Color(255, 255, 255));
        lvl_Codigo_Pedido.setText("Codigo Pedido");
        getContentPane().add(lvl_Codigo_Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, 20));

        tcantidad_unidades.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tcantidad_unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcantidad_unidadesActionPerformed(evt);
            }
        });
        tcantidad_unidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcantidad_unidadesKeyTyped(evt);
            }
        });
        getContentPane().add(tcantidad_unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 130, 30));

        tfecha_ingreso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfecha_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfecha_ingresoActionPerformed(evt);
            }
        });
        tfecha_ingreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfecha_ingresoKeyTyped(evt);
            }
        });
        getContentPane().add(tfecha_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 130, 30));

        lvl_Fecha_Ingreso1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_Fecha_Ingreso1.setForeground(new java.awt.Color(255, 255, 255));
        lvl_Fecha_Ingreso1.setText("Fecha Ingreso");
        getContentPane().add(lvl_Fecha_Ingreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, 20));

        lvl_Cantidad_Unidaes1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lvl_Cantidad_Unidaes1.setForeground(new java.awt.Color(255, 255, 255));
        lvl_Cantidad_Unidaes1.setText("Cantidad Unidaes");
        getContentPane().add(lvl_Cantidad_Unidaes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Requerido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Requerido");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Requerido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Requerido");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Requerido");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Requerido");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tid_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tid_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tid_proveedorActionPerformed

    private void tid_proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tid_proveedorKeyTyped
        char c= evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_tid_proveedorKeyTyped

    private void tnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnipActionPerformed

    private void tnipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnipKeyTyped
        char c= evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_tnipKeyTyped

    private void tnombre_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnombre_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnombre_proveedorActionPerformed

    private void tnombre_proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnombre_proveedorKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'z') && (c<' ' || c>' '))evt.consume();
    }//GEN-LAST:event_tnombre_proveedorKeyTyped

        private void limpiar(){
        tnip.setText(null);
        tid_proveedor.setText(null);
        tnombre_proveedor.setText(null);
        tfecha_ingreso.setText(null);
        tcantidad_unidades.setText(null);
        tcodigo_pedido.setText(null);
    }
    
    
    private void btn_registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrar1ActionPerformed
        conect=new Conectar();
        //Creación de un try para mostrar un mensaje en vez de un error en la consola
        try{
            Connection r2=conect.getConnection();
            //Acción que se va realizar en la base de datos
            PreparedStatement ingresar2=r2.prepareStatement("INSERT INTO pedido(codigo_pedido,cantidad) VALUES(?,?)");
            ingresar2.setString(1,tcodigo_pedido.getText());
            ingresar2.setString(2,tcantidad_unidades.getText());
            int registro2=ingresar2.executeUpdate();
            //Creación de un if
            if(registro2>0){
                JOptionPane.showMessageDialog(null,"Registrado en la tabla pedido");
                //Creación de un try para mostrar un mensaje en vez de un error en la consola
                try{
                    Connection r=conect.getConnection();
                    //Acción que se va realizar en la base de datos
                    PreparedStatement ingresar=r.prepareStatement("INSERT INTO proveedor(id_proveedor,nit,nombre_proveedor,fecha_ingreso,cantidad_unidades,codigo_pedido) VALUES(?,?,?,?,?,?)");
                    ingresar.setString(1,tid_proveedor.getText());
                    ingresar.setString(2,tnip.getText());
                    ingresar.setString(3,tnombre_proveedor.getText());
                    ingresar.setString(4,tfecha_ingreso.getText());
                    ingresar.setString(5,tcantidad_unidades.getText());
                    ingresar.setString(6,tcodigo_pedido.getText());
                    int registro=ingresar.executeUpdate();
                    //Creación de un if
                    if(registro>0){
                        JOptionPane.showMessageDialog(null,"Registrado correctamente");
                    }else{
                        JOptionPane.showMessageDialog(null,"Registro fallido");
                        limpiar();
                    }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Error en consola");
                    System.out.println("Error en el registro: "+e);
                    limpiar();
                }
            }else{
                JOptionPane.showMessageDialog(null,"No se registro en la tabla pedido");
            }
        }catch(SQLException o){
            JOptionPane.showMessageDialog(null,"Error en consola");
            System.out.println("Error en el registro: "+o);
        }
    }//GEN-LAST:event_btn_registrar1ActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        tid_proveedor.setText("");
        tnip.setText("");
        tnombre_proveedor.setText("");
        tfecha_ingreso.setText("");
        tcantidad_unidades.setText("");
        tcodigo_pedido.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void tcodigo_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcodigo_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcodigo_pedidoActionPerformed

    private void tcodigo_pedidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcodigo_pedidoKeyTyped
        char c= evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_tcodigo_pedidoKeyTyped

    private void tcantidad_unidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcantidad_unidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcantidad_unidadesActionPerformed

    private void tcantidad_unidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcantidad_unidadesKeyTyped
        char c= evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_tcantidad_unidadesKeyTyped

    private void tfecha_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfecha_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfecha_ingresoActionPerformed

    private void tfecha_ingresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfecha_ingresoKeyTyped
        char c= evt.getKeyChar();
        if((c<'0' || c>'9') && (c<'/' || c>'/'))evt.consume();
    }//GEN-LAST:event_tfecha_ingresoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_registrar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lvl_Cantidad_Unidaes1;
    private javax.swing.JLabel lvl_Codigo_Pedido;
    private javax.swing.JLabel lvl_Fecha_Ingreso1;
    private javax.swing.JLabel lvl_Id_Proveedor;
    private javax.swing.JLabel lvl_cc;
    private javax.swing.JLabel lvlv_Nombre_Proveedor;
    private javax.swing.JTextField tcantidad_unidades;
    private javax.swing.JTextField tcodigo_pedido;
    private javax.swing.JTextField tfecha_ingreso;
    private javax.swing.JTextField tid_proveedor;
    private javax.swing.JTextField tnip;
    private javax.swing.JTextField tnombre_proveedor;
    // End of variables declaration//GEN-END:variables
}
