
import java.security.Principal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sebit
 */
public class tabla_cuentass extends javax.swing.JInternalFrame {

    /**
     * Creates new form tabla_cuentass
     */
    public tabla_cuentass() {
        initComponents();
        tabla_de_ventas();
    }
void tabla_de_ventas(){
       Conectar con=new Conectar();
         Connection Conectar=con.getConnection();
        
        DefaultTableModel modelo=new DefaultTableModel(){
                 
                 
        };
            modelo.addColumn("Correo");
            modelo.addColumn("Contraseña");
            modelo.addColumn("Cedula");
            modelo.addColumn("Tipo");
            
            cuentas.setModel(modelo);
        
        String sql = "SELECT*FROM cuenta";
        
        String dato[]= new String[11];
        try {

        
        Statement st= Conectar.createStatement();
        
        ResultSet rs=st.executeQuery(sql);
        
        while(rs.next()){
           dato[0]= rs.getString(1);
          dato[1]= rs.getString(2);
          dato[2]= rs.getString(3);
          dato[3]= rs.getString(4);
            modelo.addRow(dato);
        }
        cuentas.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuentas = new javax.swing.JTable();
        btm_actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Cuentas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        cuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(cuentas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 760, 190));

        btm_actualizar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btm_actualizar.setText("Actualizar tabla");
        btm_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 285, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_actualizarActionPerformed
tabla_de_ventas();
    }//GEN-LAST:event_btm_actualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_actualizar;
    private javax.swing.JTable cuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
