
import java.security.Principal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manci
 */
public class tabla_proveedoress extends javax.swing.JInternalFrame {

    /**
     * Creates new form tabla_proveedoress
     */
    public tabla_proveedoress() {
        initComponents();
        tabla_de_proveedoress();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_proveedor = new javax.swing.JTable();
        btm_actualizar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tabla proveedor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Listado de proveedores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jScrollPane1.setViewportView(tabla_proveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 660, 190));

        btm_actualizar.setText("Actualizar tabla");
        btm_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btm_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        fondo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_3.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_actualizarActionPerformed
        tabla_de_proveedoress();
    }//GEN-LAST:event_btm_actualizarActionPerformed
void tabla_de_proveedoress(){
       Conectar con=new Conectar();
         Connection Conectar=con.getConnection();
        
        DefaultTableModel modelo=new DefaultTableModel(){
                 
                 
        };
            modelo.addColumn("id proveedor");
            modelo.addColumn("NIT");
            modelo.addColumn("Nombre");
            modelo.addColumn("Fecha ingreso");
            modelo.addColumn("Cantidad unidades");
            modelo.addColumn("Codigo pedido");
            tabla_proveedor.setModel(modelo);
        
        String sql = "SELECT*FROM proveedor";
        
        String dato[]= new String[11];
        try {

        
        Statement st= Conectar.createStatement();
        
        ResultSet rs=st.executeQuery(sql);
        
        while(rs.next()){
           dato[0]= rs.getString(1);
          dato[1]= rs.getString(2);
          dato[2]= rs.getString(3);
          dato[3]= rs.getString(4);
          dato[4]= rs.getString(5);
          dato[5]= rs.getString(6);
            modelo.addRow(dato);
        }
        tabla_proveedor.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_actualizar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_proveedor;
    // End of variables declaration//GEN-END:variables
}
